services:
  - type: web
    name: snapchef-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false 