services:
  - type: web
    name: snapchef-backend
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: OPENAI_API_KEY
        sync: false 